spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

auth:
  api-url: ${AUTH_API_URL}
  admin-key: ${AUTH_ADMIN_KEY}

neversion:
  gateway:
    secret: ${NEVERSION_GATEWAY_SECRET}